#!/usr/bin/env node
// Generates index.html from content.js (this page's own prose + page
// order) plus each referenced piece's own, real ../explainer-<name>/
// index.html (read fresh from disk every run -- never a stale
// hand-copy). This keeps a single source of truth for each piece's own
// markup shape, which a hand-copied version can't: change a piece's
// own index.html and this page picks it up automatically the next time
// this script runs, the same way its script.js/style.css already do
// via <script src>/<link href>.
//
// Usage: node build.js   (run from this directory)
// For the public mirror repo (unprefixed piece directories):
//   PIECE_DIR_PREFIX= node build.js
//
// index.html is a committed, generated file -- readable and viewable
// on its own (open it directly, no build step needed just to look at
// it), but not meant to be hand-edited: edit content.js (for text or
// page order) or a piece's own index.html (for that piece's own markup
// shape) instead, then re-run this script and commit both the source
// change and the regenerated index.html.

"use strict";

const fs = require("fs");
const path = require("path");
const content = require("./content.js");

const HERE = __dirname;

// Each piece's own directory is named `explainer-<name>` in *this* repo
// (the IBM monorepo) but just `<name>` (no prefix) in the public mirror
// repo (github.com/lastras/explainer-information-logic), which predates
// this convention and already has public links pointing at e.g.
// `less-is-more/`, not `explainer-less-is-more/`. Overridable via the
// PIECE_DIR_PREFIX env var so the exact same content.js/build.js can
// generate a correct index.html for either repo -- e.g., from within a
// copy of this directory placed at that mirror's own root:
// `PIECE_DIR_PREFIX= node build.js`. Defaults to this repo's own
// convention so plain `node build.js` is unchanged.
const PIECE_DIR_PREFIX = process.env.PIECE_DIR_PREFIX != null ? process.env.PIECE_DIR_PREFIX : "explainer-";

// This page is a narrative wrapper around several pieces that also
// exist as standalone, self-contained explainers under ../explainer-*/.
// Kept here (not in content.js) since it documents this *build*
// mechanism, not the page's own prose content.
const ARCHITECTURE_COMMENT = `<!-- This page is a narrative wrapper around several pieces that also
     exist as standalone, self-contained explainers, each under its own
     sibling directory (see build.js's own PIECE_DIR_PREFIX for this
     repo's exact naming). Each piece's own native markup
     (.scroll-track > .pinned > canvas + .legend) is inlined directly
     into this page's own scroll flow, wrapped in a
     <section class="piece-block piece-X">, rather than embedded via
     <iframe>. That's a deliberate change from an earlier version of
     this file: an iframe's own box has to be given some fixed CSS
     height shorter than the viewport to sit "full-bleed" inside
     surrounding prose, but each piece's own .pinned graphic only
     renders uncropped once *it* fills the full viewport
     (position: sticky; height: 100vh) -- so a shorter iframe box left
     the graphic visibly cropped across a wide range of scroll
     positions, with no workable fix that didn't involve either
     scripting the user's own scroll position (rejected -- see this
     file's own history for why) or leaving multiple screens of
     "nothing changes" scrolling per piece. Inlining each piece's own
     real markup, at its own real height, is what actually reproduces
     its standalone (uncropped, non-scripted) scroll behavior here.

     Unlike an even earlier version of this file, that markup is no
     longer hand-copied here either: this file is generated by
     build.js, which reads each piece's own index.html fresh off disk
     every time it runs (see build.js's own comments). Only the prose
     between pieces (content.js) and the page's own order are this
     file's own real source; everything else is a live reflection of
     each piece's own directory.

     Every piece reuses the same DOM ids (#scene, #legend, etc.) since
     each was built to be the only script on its own page. Loaded
     together here, each piece's own script.js scopes its own
     document.getElementById-equivalent lookups to its own nearest
     .piece-block ancestor (via document.currentScript.closest), and
     each piece's own style.css selectors are all prefixed with that
     same piece's own class (.piece-entailment, .piece-no-need-to-know,
     etc.) -- see each piece's own script.js/style.css for the
     mechanism. No id/CSS collisions result from several copies of the
     same ids coexisting in one document.

     Pieces whose graphic isn't pure canvas (e.g. "Reasoning Amplifies
     Information," which overlays two <img> SVGs) point their own
     same-directory asset paths ("assets/...") at a same-directory path
     that resolves fine standalone, but would resolve wrong once
     inlined here (relative to *this* file's own URL, not that piece's
     directory) -- build.js rewrites any such relative src/href
     attribute in a piece's markup to point at that piece's own
     directory instead (see extractPieceMarkup below). -->`;

// Pulls a piece's own <body> content (everything between the opening
// <body ...> tag and its own closing <script src="script.js"> line),
// verbatim -- comments and all -- so this stays a true mechanical
// reflection of that piece's own file, not a hand-curated subset of it.
function extractPieceMarkup(name) {
  const file = path.join(HERE, "..", `${PIECE_DIR_PREFIX}${name}`, "index.html");
  const html = fs.readFileSync(file, "utf8");

  const bodyTagStart = html.indexOf("<body");
  const bodyOpenEnd = html.indexOf(">", bodyTagStart) + 1;
  const scriptTag = '<script src="script.js">';
  const scriptStart = html.indexOf(scriptTag);
  if (bodyTagStart < 0 || bodyOpenEnd <= 0 || scriptStart < 0) {
    throw new Error(`Could not extract <body> markup from ${file}`);
  }

  let markup = html.slice(bodyOpenEnd, scriptStart).trim();

  // Rewrite same-directory relative src/href attributes (e.g. this
  // piece's own asset SVGs) to point at ../<prefix><name>/ instead --
  // left untouched: absolute URLs (http/https), root-relative (/...),
  // fragment-only (#...), and anything already rewritten.
  markup = markup.replace(/(src|href)="(?!https?:|\/\/|\/|#)([^"]+)"/g, `$1="../${PIECE_DIR_PREFIX}${name}/$2"`);

  return markup;
}

function renderSection(section) {
  if (section.type === "prose") {
    return `<section class="${section.className}">${section.html}\n</section>`;
  }
  if (section.type === "piece") {
    const markup = extractPieceMarkup(section.name);
    return (
      `<section class="piece-block piece-${section.name}">\n` +
      `  ${markup}\n` +
      `  <script src="../${PIECE_DIR_PREFIX}${section.name}/script.js"></script>\n` +
      `</section>`
    );
  }
  throw new Error(`Unknown section type: ${JSON.stringify(section)}`);
}

function build() {
  const pieceNames = content.sections.filter((s) => s.type === "piece").map((s) => s.name);
  const styleLinks = pieceNames.map((name) => `<link rel="stylesheet" href="../${PIECE_DIR_PREFIX}${name}/style.css">`).join("\n");

  const html = `<!-- GENERATED FILE -- do not edit directly. Edit content.js (for this
     page's own text/order) or a piece's own index.html (for that
     piece's own markup shape) under ../explainer-<name>/, then run
     \`node build.js\` from this directory and commit both. -->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${content.title}</title>
<link rel="stylesheet" href="style.css">
${styleLinks}
</head>
<body>

${ARCHITECTURE_COMMENT}

<header class="masthead prose">
  <h1>${content.masthead.h1}</h1>
  <p class="subhead">${content.masthead.subhead.trim()}</p>
</header>

${content.sections.map(renderSection).join("\n\n")}

<script src="script.js"></script>
</body>
</html>
`;

  fs.writeFileSync(path.join(HERE, "index.html"), html);
  console.log(`Wrote index.html (${pieceNames.length} pieces: ${pieceNames.join(", ")})`);
}

build();
